### ISSUE TITLE
Usage with Content-Security-Policy

### ISSUE THREAD

**Issue by superstes** [piccolo-orm/piccolo_theme#82]
Greetings!

First of all - thank you for providing this nice theme! Really love it so far (:

As I configured the security feature [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), I found that the theme uses inline JS and styles.

I'm not familiar with the structure of Sphinx themes, but this looks a little odd to me.

For reference - this CSP entry works: `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';">`

Without `unsafe-eval` and `unsafe-inline` the theme fails.

Of course - its not that important as XSS is no real threat to a static docs page. Just wanted to mention it

**Comment by dantownsend** [comment]
Hi @superstes,

You're right, it has some inline scripts:

https://github.com/piccolo-orm/piccolo_theme/blob/master/piccolo_theme/components/dark_mode_toggle.html
https://github.com/piccolo-orm/piccolo_theme/blob/master/piccolo_theme/components/notification_banner.html

I could move them into script files. The only reason they're inline is because it felt cleaner at the time to put the the JS next to the relevant HTML.

I didn't realise that CSP prevents inline scripts, but it does make sense now I think about it.

https://content-security-policy.com/examples/allow-inline-script/

I'll try and move the JS into separate files in a future release - thanks!

**Comment by superstes** [comment]
Nice, thank you :+1: 

Yeah - CSP blocks inline scripts by default as they are often used to exploit XSS/injection vulnerabilities.
