### ISSUE TITLE
Page Content - Scroll Bar on Firefox

### ISSUE THREAD

**Issue by superstes** [piccolo-orm/piccolo_theme#86]
Greetings.

I've got a [long docs page](https://docs.o-x-l.at/proxy/reverse_haproxy.html#rate-limits) and am not able to scroll to the end of the `Page content` in FireFox, as the scroll-bar of the whole site overlaps with this one :/
It's an edge-case - but could be improved if the scroll-bar of the `Page content` could be moved to the left.

![image](https://github.com/user-attachments/assets/832a305f-ec62-49d5-a469-fb02ef3b9d0b)

It works in Chromium, as we get two scroll-bars there:
![image](https://github.com/user-attachments/assets/b9ba673a-84f8-4935-9bf1-e2a9a8fec9ac)

If this FireFox setting is enabled, it works. But I guess other users will run into the same issue.
![image](https://github.com/user-attachments/assets/f3df77f4-4d09-4dca-b5f0-b885c2b19793)

I'm not sure if this is worth fixing.. but wanted to report it anyways.

**Comment by superstes** [comment]
Note: Was also not using a Mouse at that time. Hovering the 'Page Content' area and using the mouse-whell works as designed.

**Comment by dantownsend** [comment]
I see what you're saying.

I tried it in FireFox on my laptop, and when I scroll with the cursor over the center of the page it scrolls the whole page, but when the cursor is over the sidebar, it scrolls that instead.

But it does look a bit weird, because sometimes I see the overlapping scrollbars, and if you're reliant on using them rather than the mouse wheel or trackpad, it would be annoying.

I'm not sure what the best solution is - we could add some right margin to the sidebar, so the scrollbar doesn't overlap with the page's scrollbar.

The only other reference I could find to it online was this: https://www.reddit.com/r/firefox/comments/1d8ubwx/firefox_overlaps_two_scroll_bars_so_i_cant_use_one/

Which operating system are you using?

**Comment by superstes** [comment]
Yeah - I think that's the post I've also found.
I'm on Linux (Ubuntu).

As I said - probably no problem for 99.99% of use-cases/users.
Could be stamped off as 'very edgy edge-case' ([or even firefox 'bug'](https://connect.mozilla.org/t5/ideas/scroll-bar-width-and-customization-options/idi-p/5320)) and closed (;
